Initial landing page files
noazaj/travel-companion pull request #3
Opened 2024-07-14 19:36 UTC by flattumc

2024-07-14 19:39 UTC, flattumc commented
Added initial web files for the landing page. This includes the logo, mount Fugi img, and another image for later testing.

Files added:
* index.html
* styles.css

This is the first iteration of the landing page. Everything is housed a central "app" folder which will be used long term. 
![Screenshot 2024-07-14 143859](https://github.com/user-attachments/assets/14713efd-25c3-4440-8c53-354c641118fc)

2024-07-14 22:05 UTC, flattumc commented
I've also included the first mock up of the planning page:

![Screenshot 2024-07-14 170330](https://github.com/user-attachments/assets/f0015fa9-d353-4834-bc38-50036ddb19d7)

2024-07-14 22:33 UTC, nswai983 requested changes
Love the pages overall! Have a few comments on the plan-a-trip.html, but otherwise looks good.

2024-07-14 22:33 UTC, nswai983 commented on app/web/plan-a-trip.html
Love these pages! The desires are great, and I think they really fit the theme of what we're going for.

I did notice on my laptop screen (2560x1600), the top text of the trip planning page overlaps with the headers. Would you be able to add some padding here to ensure they don't overlap? See image below for what I'm seeing.

![tripPlannerOverlap](https://github.com/user-attachments/assets/681828a0-cffa-4bae-8c2a-cd26ae541648)

2024-07-14 22:33 UTC, nswai983 commented on app/web/plan-a-trip.html
Having a back button on this page would be good too.

2024-07-15 03:35 UTC, flattumc commented on app/web/plan-a-trip.html
App currently supports backwards navigation through header

2024-07-15 03:36 UTC, flattumc commented on app/web/plan-a-trip.html
Updated media settings to account for different variations of zoom (90%,100%,110%,and 125%). This should help assist with padding issues seen above as well as future issues of overlap

2024-07-16 03:04 UTC, nswai983 approved these changes
Changes look great. The addition of accessibility settings makes sure nothing overlaps!

2024-07-16 03:04 UTC, merged